name: extendedobjects
---
Image:
  extensions:
    - ExtendedImage

File:
  extensions:
    - ExtendedFile

Upload:
  extensions:
    - ExtendedUpload

GDBackend:
  extensions:
    ExtendedGDBackend

Date:
  extensions:
    - ExtendedDate