---
Name: customroutes
After: framework/routes#coreroutes
---
Director:
  rules:
    'AudioFileDataExtractionTask' : 'AudioFileDataExtractionTask'
    'VideoFileDataExtractionTask' : 'VideoFileDataExtractionTask'